#!/usr/bin/env python3
"""
Generate VAPID keys for Web Push notifications and save to .env file.
Run this once before starting the server.
"""

import os
import sys
import base64
from pathlib import Path


def generate_vapid_keys():
    """Generate VAPID keys using py_vapid / cryptography."""
    try:
        from cryptography.hazmat.primitives.asymmetric import ec
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.backends import default_backend

        # Generate EC key pair (P-256 curve for VAPID)
        private_key = ec.generate_private_key(ec.SECP256R1(), default_backend())

        # Private key as PEM
        private_pem = private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        ).decode("utf-8").strip()

        # Public key as uncompressed point in URL-safe base64
        public_key_bytes = private_key.public_key().public_bytes(
            encoding=serialization.Encoding.X962,
            format=serialization.PublicFormat.UncompressedPoint,
        )
        public_key_b64 = base64.urlsafe_b64encode(public_key_bytes).rstrip(b"=").decode("utf-8")

        return private_pem, public_key_b64

    except ImportError:
        print("cryptography library not found. Installing requirements first...")
        sys.exit(1)


def main():
    env_path = Path(__file__).parent / ".env"

    # Check if .env already has VAPID keys
    if env_path.exists():
        content = env_path.read_text(encoding="utf-8")
        if "VAPID_PRIVATE_KEY" in content and "VAPID_PUBLIC_KEY" in content:
            print(".env already contains VAPID keys. Skipping generation.")
            print("Delete .env to regenerate keys.")

            # Still print the public key for frontend configuration
            for line in content.splitlines():
                if line.startswith("VAPID_PUBLIC_KEY="):
                    public_key = line.split("=", 1)[1].strip().strip('"').strip("'")
                    print(f"\nVAPID Public Key (for frontend):\n{public_key}")
            return

    print("Generating VAPID keys...")
    try:
        private_key_pem, public_key_b64 = generate_vapid_keys()
    except Exception as e:
        print(f"Error generating VAPID keys: {e}")
        print("Make sure cryptography is installed: pip install cryptography")
        sys.exit(1)

    # Escape newlines in private key PEM for .env
    # Store private key as single-line by removing headers and joining
    pem_lines = private_key_pem.strip().splitlines()
    # Keep full PEM but escape for .env (use double-quote wrapping)
    private_key_env = private_key_pem.replace("\n", "\\n")

    env_content = f'''# 献立共有アプリ - Environment Configuration
# Generated by setup_vapid.py

# VAPID Keys for Web Push Notifications
VAPID_PRIVATE_KEY="{private_key_env}"
VAPID_PUBLIC_KEY="{public_key_b64}"
VAPID_CLAIMS_EMAIL="mailto:admin@kondate.local"

# Server Configuration
HOST=0.0.0.0
PORT=8000
'''

    env_path.write_text(env_content, encoding="utf-8")
    print(f".env file created at: {env_path}")
    print(f"\nVAPID Public Key (for frontend configuration):\n{public_key_b64}")
    print("\nSetup complete! You can now start the server.")


if __name__ == "__main__":
    main()
