from datetime import datetime, timezone, timedelta

def _ago(hours: int) -> str:
    t = datetime.now(timezone.utc) - timedelta(hours=hours)
    return t.isoformat()

MOCK_ARTICLES = [
    {
        "id": "mock001",
        "title": "LeBron James signs two-year extension with Lakers",
        "summary": "According to official team announcement, LeBron James has agreed to a two-year contract extension, committing to the Los Angeles Lakers through the 2026-27 season.",
        "url": "https://www.nba.com/news/lebron-extension",
        "source": "NBA.com",
        "published": _ago(1),
        "tier": 1,
        "credibility_label": "公式",
        "credibility_color": "blue",
    },
    {
        "id": "mock002",
        "title": "Anthony Davis dominates with 38-point, 14-rebound performance",
        "summary": "Anthony Davis put up a monster performance Tuesday night, finishing with 38 points and 14 rebounds to lead the Los Angeles Lakers past the Golden State Warriors 118-105.",
        "url": "https://www.espn.com/nba/story/davis-performance",
        "source": "ESPN NBA",
        "published": _ago(3),
        "tier": 2,
        "credibility_label": "信頼性高",
        "credibility_color": "green",
    },
    {
        "id": "mock003",
        "title": "Lakers reportedly targeting veteran point guard in free agency",
        "summary": "Per sources close to the team, the Los Angeles Lakers are exploring options in free agency and have expressed interest in a veteran point guard to provide depth off the bench.",
        "url": "https://bleacherreport.com/lakers-free-agency",
        "source": "Bleacher Report",
        "published": _ago(5),
        "tier": 4,
        "credibility_label": "噂",
        "credibility_color": "orange",
    },
    {
        "id": "mock004",
        "title": "Lakers hold pre-draft workout with top prospects",
        "summary": "The Los Angeles Lakers held a pre-draft workout Tuesday, getting an up-close look at several top prospects ahead of the NBA Draft. Scouts were impressed with multiple players.",
        "url": "https://www.cbssports.com/nba/lakers-draft",
        "source": "CBS Sports NBA",
        "published": _ago(8),
        "tier": 2,
        "credibility_label": "信頼性高",
        "credibility_color": "green",
    },
    {
        "id": "mock005",
        "title": "Lakers coaching staff evaluating starting lineup changes for playoffs",
        "summary": "Head coach JJ Redick is reportedly considering lineup adjustments as the Lakers prepare for the postseason push. Multiple lineup combinations have been tested in practice.",
        "url": "https://lakersnation.com/lineup-changes",
        "source": "Lakers Nation",
        "published": _ago(10),
        "tier": 3,
        "credibility_label": "信頼性中",
        "credibility_color": "yellow",
    },
    {
        "id": "mock006",
        "title": "Trade rumors: Lakers could target All-Star wing before deadline",
        "summary": "According to multiple league insiders, the Lakers might be exploring a trade for an All-Star caliber wing player before the February trade deadline. The team is expected to be aggressive.",
        "url": "https://sports.yahoo.com/nba/lakers-trade",
        "source": "Yahoo Sports NBA",
        "published": _ago(14),
        "tier": 4,
        "credibility_label": "噂",
        "credibility_color": "orange",
    },
    {
        "id": "mock007",
        "title": "Austin Reaves scores career-high 35 points in Lakers victory",
        "summary": "Austin Reaves set a new career high with 35 points on 13-of-20 shooting, including 7-of-12 from three-point range, as the Lakers defeated the Houston Rockets 127-118 on Thursday night.",
        "url": "https://www.espn.com/nba/reaves-career-high",
        "source": "ESPN NBA",
        "published": _ago(18),
        "tier": 2,
        "credibility_label": "信頼性高",
        "credibility_color": "green",
    },
    {
        "id": "mock008",
        "title": "Lakers' Rui Hachimura expected to miss 2-3 weeks with ankle sprain",
        "summary": "The Los Angeles Lakers announced that forward Rui Hachimura has been diagnosed with a mild ankle sprain and is expected to miss approximately 2-3 weeks. He will be re-evaluated next week.",
        "url": "https://www.nba.com/news/hachimura-injury",
        "source": "NBA.com",
        "published": _ago(22),
        "tier": 1,
        "credibility_label": "公式",
        "credibility_color": "blue",
    },
    {
        "id": "mock009",
        "title": "Silver Screen & Roll: Grading the Lakers' first half of the season",
        "summary": "We take a deep look at the Lakers' performance through the first half of the season, grading each key contributor and what it means for their playoff chances.",
        "url": "https://www.silverscreenandroll.com/midseason-grades",
        "source": "Silver Screen & Roll",
        "published": _ago(26),
        "tier": 3,
        "credibility_label": "信頼性中",
        "credibility_color": "yellow",
    },
    {
        "id": "mock010",
        "title": "LeBron eyeing milestone as he approaches all-time scoring record",
        "summary": "LeBron James is approaching yet another historic milestone this week. A strong performance in the next few games could see him add another record to his already legendary resume.",
        "url": "https://clutchpoints.com/lakers-lebron-milestone",
        "source": "ClutchPoints Lakers",
        "published": _ago(30),
        "tier": 3,
        "credibility_label": "信頼性中",
        "credibility_color": "yellow",
    },
    {
        "id": "mock011",
        "title": "Lakers front office monitoring buyout market for additional shooting",
        "summary": "League sources indicate the Los Angeles Lakers are monitoring the buyout market as the trade deadline approaches, with a focus on adding shooting and wing depth to their roster.",
        "url": "https://lakersnation.com/buyout-market",
        "source": "Lakers Nation",
        "published": _ago(36),
        "tier": 4,
        "credibility_label": "噂",
        "credibility_color": "orange",
    },
    {
        "id": "mock012",
        "title": "D'Angelo Russell trade talks heating up, per insider",
        "summary": "Multiple teams have reportedly expressed interest in Lakers guard D'Angelo Russell, with trade talks expected to intensify ahead of the deadline according to a well-connected NBA insider.",
        "url": "https://clutchpoints.com/russell-trade-talks",
        "source": "ClutchPoints Lakers",
        "published": _ago(42),
        "tier": 4,
        "credibility_label": "噂",
        "credibility_color": "orange",
    },
]
